apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: platform-api
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: opa
          image: openpolicyagent/opa@sha256:35a093d9ae828373cf88f68ecaa8189ab26287468074a3b78f0601d9c8b7a4f5
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "/policies/authz.rego"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: policy
              mountPath: /policies
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8181
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: policy
          configMap:
            name: opa-policy