apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-api-quota
  namespace: platform-api
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    pods: "10"