apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-hardening
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-readonly-rootfs
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - platform-api
      validate:
        message: "Containers must set readOnlyRootFilesystem: true."
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true

    - name: require-resource-requests-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - platform-api
      validate:
        message: "Containers must set explicit resource requests (cpu, memory) and a CPU limit."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"