name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.9.0"
      - name: Terraform fmt check
        run: terraform fmt -check -recursive terraform/
      - name: Terraform validate
        run: |
          cd terraform/environments/dev/aws
          terraform init -backend=false
          terraform validate

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "1.26"
      - name: Build
        working-directory: platform-api
        run: go build ./...
      - name: Test
        working-directory: platform-api
        run: go test ./...
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: [terraform, go]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::133857166442:role/github-actions-platform-api
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login
      - name: Build and push image
        working-directory: platform-api
        run: |
          docker build --platform linux/amd64 -t ${{ steps.ecr-login.outputs.registry }}/platform-api:${{ github.sha }} .
          docker push ${{ steps.ecr-login.outputs.registry }}/platform-api:${{ github.sha }}